### ISSUE TITLE
Экран главного меню

### ISSUE THREAD

**Issue by savegame** [savegame/bada-devel#4]
Нужен класс экрана главного меню, его нужно наследовать от ExtendedScreen класса.
Что нужно внутри: 
Графический интерфейс (пока простой) из трех кнопок: игра, настройки, выход. Нажатие на кнопку игра выкидывает на экран выбора уровня, там пока будут тестовые уровни, менеджер списка уровне еще на потходе, пока даже не начал писать я )

**Comment by TonyForge** [comment]
Вроде чтобы дальше по этой задаче продвинуться нужен уже менеджер уровней. Ну и можно новый issue создать конкретно для экрана выбора уровня.

Вобщем сделал pull-request по этой задачке, посмотри что там и как.

**Comment by savegame** [comment]
сейчас поглядим, выгружу у себя твои изменения ) 
а вообще в будущем думаю ты сам будешь сливать и проверять ) только все же надо ветку разработки отщипить от master, и от нее уже отщиплять остальное

**Comment by savegame** [comment]
слил ветки
