### ISSUE TITLE
Менеджер игровых уровней

### ISSUE THREAD

**Issue by savegame** [savegame/bada-devel#5]
Нужен класс который будет отвечать за загрузку игровых уровней, так же он должен предоставлять список доступных уровней. Для каждого уровня должна быть иныормация, такая как. : файл настроек уровня (который должен принимать в себя загрузчик уровня), имя уровня, картинка ( какая нибудь картинка которая будет вставлена в меню игровом), может еще какая иныормация, типа сложности, кол-ва звездочек, кол-во секретов и т.п.

**Comment by savegame** [comment]
Теперь еще нужно сделать что бы при нажатии на кнопку Play, либо грузился сразу уровень Box2DTestLevel, либо открывался MMenu_LevelSelect, там где была бы кнопка загрузки Box2DTestLevel
Загрузку можно сделать так ( mainMenuStage - это объект класса MainMenuStage ):

``` java
game.setScreen( new Box2DTestLevel(game) );
mainMenuStage.dispose();
```

**Comment by TonyForge** [comment]
Кстати эти Screen автоматически dispose не вызывают, только вручную.

Надо видимо как-то так делать:
game.getScreen().dispose();
game.SetScreen(new Box2DTestLevel(game));

**Comment by savegame** [comment]
да, dispose только руками вызывать, ничего там автоматически не происходит, если тока не переопределить метод setScreen который внутри себя будет dispose для предидущего screen вызывать, и еще, не стоит вызывать dispose до того как screen не замещен новым, поэтому выше я написал 

``` java
Screen oldScreen = game.getScreen();
game.setScreen( new Box2DTestLevel(game) );
oldScreen.dispose();
```

**Comment by savegame** [comment]
сделано в задачке #6
