### ISSUE TITLE
Реализовать заглушки для ресурсов

### ISSUE THREAD

**Issue by TonyForge** [savegame/bada-devel#7]
Сейчас не очень понятно как должен реагировать объект, если нужные ему текстуры не найдены при game.asset.isLoaded, остановить игру он не может, какую-то дефолтную текстуру каждый раз создавать не рационально, всюду проверять загружен ли ресурс тоже плохо, в итоге все это потенциально ведет к вылету приложения.

ExtendedScreen при загрузке ресурса мог бы подменять не найденные ресурсы заглушками. Для текстур по крайней мере такая заглушка бы пригодилась (просто небольшая черную текстурка создаваемая кодом).

Ну либо можно отказаться от практики верификации ресурсов вообще, т.к. в случае сборки APK все равно все ресурсы внедряются в него и потеряться не могут.

**Comment by savegame** [comment]
Заглушку все равно сделаем, будет проще, так на каждый класс ресурсов нужно )

**Comment by savegame** [comment]
Нужно ресурсы при загрзке подменять заглушками, если не удалось загрузить их, тогда не нужно будет проверять их доступность при попытке импользовать. Так же, если ресурс не загрузился, нужно куда нибудь в логнер писать сообщение что ресурс просран )

**Comment by savegame** [comment]
Ты @TonyForge видел ворованную версию _Half-Life 2_? Там вот ,когда не было какой либо модели в игре, появлялась моделька надписи _ERROR_, например там что нибудть взрывалось по скрипту, и оттуда вылетали куча надписей _ERROR_. А если не было какой то текстры, то вместо не рисовалась текстура черно-розовой клеточки. Вот такие заглушки и нам надо сделать, вместо частиц какую нить маленькую, вместо текстуры какую нить еще, вместо шрифта и вместо звука...

**Comment by TonyForge** [comment]
Начал новую ветку по этой задаче:
https://github.com/savegame/bada-devel/tree/lost-resource-dummies

**Comment by TonyForge** [comment]
Тут решили без заглушек пока жить, ветку удалил :)
